
sudo: required

services:
  - docker

install:
  - docker login -e=${DOCKER_HUB_EMAIL} -u=${DOCKER_HUB_USERNAME} -p=${DOCKER_HUB_PASSWORD}
  - DOCKER_TAG=$(grep 'awscli===' Dockerfile | awk -F= '{print $4}')

script:
  - docker build -t ${DOCKER_IMAGE}:${DOCKER_TAG} .
  - docker push ${DOCKER_IMAGE}:${DOCKER_TAG}
